// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`

`include "prim_assert.sv"

module puf_reg_top (
  input clk_i,
  input rst_ni,
  input  tlul_pkg::tl_h2d_t tl_i,
  output tlul_pkg::tl_d2h_t tl_o,
  // To HW
  output puf_reg_pkg::puf_reg2hw_t reg2hw, // Write
  input  puf_reg_pkg::puf_hw2reg_t hw2reg, // Read

  // Integrity check errors
  output logic intg_err_o
);

  import puf_reg_pkg::* ;

  localparam int AW = 6;
  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;
  logic reg_busy;

  tlul_pkg::tl_h2d_t tl_reg_h2d;
  tlul_pkg::tl_d2h_t tl_reg_d2h;


  // incoming payload check
  logic intg_err;
  tlul_cmd_intg_chk u_chk (
    .tl_i(tl_i),
    .err_o(intg_err)
  );

  // also check for spurious write enables
  logic reg_we_err;
  logic [13:0] reg_we_check;
  prim_reg_we_check #(
    .OneHotWidth(14)
  ) u_prim_reg_we_check (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .oh_i  (reg_we_check),
    .en_i  (reg_we && !addrmiss),
    .err_o (reg_we_err)
  );

  logic err_q;
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      err_q <= '0;
    end else if (intg_err || reg_we_err) begin
      err_q <= 1'b1;
    end
  end

  // integrity error output is permanent and should be used for alert generation
  // register errors are transactional
  assign intg_err_o = err_q | intg_err | reg_we_err;

  // outgoing integrity generation
  tlul_pkg::tl_d2h_t tl_o_pre;
  tlul_rsp_intg_gen #(
    .EnableRspIntgGen(1),
    .EnableDataIntgGen(1)
  ) u_rsp_intg_gen (
    .tl_i(tl_o_pre),
    .tl_o(tl_o)
  );

  assign tl_reg_h2d = tl_i;
  assign tl_o_pre   = tl_reg_d2h;

  tlul_adapter_reg #(
    .RegAw(AW),
    .RegDw(DW),
    .EnableDataIntgGen(0)
  ) u_reg_if (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),

    .tl_i (tl_reg_h2d),
    .tl_o (tl_reg_d2h),

    .en_ifetch_i(prim_mubi_pkg::MuBi4False),
    .intg_error_o(),

    .we_o    (reg_we),
    .re_o    (reg_re),
    .addr_o  (reg_addr),
    .wdata_o (reg_wdata),
    .be_o    (reg_be),
    .busy_i  (reg_busy),
    .rdata_i (reg_rdata),
    .error_i (reg_error)
  );

  // cdc oversampling signals

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = addrmiss | wr_err | intg_err;

  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic ctrl_signals_we;
  logic ctrl_signals_enable_puf_qs;
  logic ctrl_signals_enable_puf_wd;
  logic ctrl_signals_mode_puf_qs;
  logic ctrl_signals_mode_puf_wd;
  logic ctrl_signals_ready_cha_qs;
  logic ctrl_signals_ready_cha_wd;
  logic state_signals_response_valid_bit_qs;
  logic state_signals_response_done_2bit_qs;
  logic challenge_0_we;
  logic [31:0] challenge_0_qs;
  logic [31:0] challenge_0_wd;
  logic challenge_1_we;
  logic [31:0] challenge_1_qs;
  logic [31:0] challenge_1_wd;
  logic challenge_2_we;
  logic [31:0] challenge_2_qs;
  logic [31:0] challenge_2_wd;
  logic challenge_3_we;
  logic [31:0] challenge_3_qs;
  logic [31:0] challenge_3_wd;
  logic [31:0] response_0_qs;
  logic [31:0] response_1_qs;
  logic [31:0] response_2_qs;
  logic [31:0] response_3_qs;
  logic [31:0] response_4_qs;
  logic [31:0] response_5_qs;
  logic [31:0] response_6_qs;
  logic [31:0] response_7_qs;

  // Register instances
  // R[ctrl_signals]: V(False)
  logic ctrl_signals_qe;
  logic [2:0] ctrl_signals_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_ctrl_signals0_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&ctrl_signals_flds_we),
    .q_o(ctrl_signals_qe)
  );
  //   F[enable_puf]: 0:0
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_signals_enable_puf (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_signals_we),
    .wd     (ctrl_signals_enable_puf_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (ctrl_signals_flds_we[0]),
    .q      (reg2hw.ctrl_signals.enable_puf.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_signals_enable_puf_qs)
  );
  assign reg2hw.ctrl_signals.enable_puf.qe = ctrl_signals_qe;

  //   F[mode_puf]: 1:1
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_signals_mode_puf (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_signals_we),
    .wd     (ctrl_signals_mode_puf_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (ctrl_signals_flds_we[1]),
    .q      (reg2hw.ctrl_signals.mode_puf.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_signals_mode_puf_qs)
  );
  assign reg2hw.ctrl_signals.mode_puf.qe = ctrl_signals_qe;

  //   F[ready_cha]: 2:2
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_signals_ready_cha (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_signals_we),
    .wd     (ctrl_signals_ready_cha_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (ctrl_signals_flds_we[2]),
    .q      (reg2hw.ctrl_signals.ready_cha.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_signals_ready_cha_qs)
  );
  assign reg2hw.ctrl_signals.ready_cha.qe = ctrl_signals_qe;


  // R[state_signals]: V(False)
  //   F[response_valid_bit]: 0:0
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRO),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_state_signals_response_valid_bit (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (1'b0),
    .wd     ('0),

    // from internal hardware
    .de     (hw2reg.state_signals.response_valid_bit.de),
    .d      (hw2reg.state_signals.response_valid_bit.d),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.state_signals.response_valid_bit.q),
    .ds     (),

    // to register interface (read)
    .qs     (state_signals_response_valid_bit_qs)
  );

  //   F[response_done_2bit]: 1:1
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRO),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_state_signals_response_done_2bit (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (1'b0),
    .wd     ('0),

    // from internal hardware
    .de     (hw2reg.state_signals.response_done_2bit.de),
    .d      (hw2reg.state_signals.response_done_2bit.d),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.state_signals.response_done_2bit.q),
    .ds     (),

    // to register interface (read)
    .qs     (state_signals_response_done_2bit_qs)
  );


  // Subregister 0 of Multireg challenge
  // R[challenge_0]: V(False)
  logic challenge_0_qe;
  logic [0:0] challenge_0_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_challenge0_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&challenge_0_flds_we),
    .q_o(challenge_0_qe)
  );
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_challenge_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (challenge_0_we),
    .wd     (challenge_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (challenge_0_flds_we[0]),
    .q      (reg2hw.challenge[0].q),
    .ds     (),

    // to register interface (read)
    .qs     (challenge_0_qs)
  );
  assign reg2hw.challenge[0].qe = challenge_0_qe;


  // Subregister 1 of Multireg challenge
  // R[challenge_1]: V(False)
  logic challenge_1_qe;
  logic [0:0] challenge_1_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_challenge1_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&challenge_1_flds_we),
    .q_o(challenge_1_qe)
  );
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_challenge_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (challenge_1_we),
    .wd     (challenge_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (challenge_1_flds_we[0]),
    .q      (reg2hw.challenge[1].q),
    .ds     (),

    // to register interface (read)
    .qs     (challenge_1_qs)
  );
  assign reg2hw.challenge[1].qe = challenge_1_qe;


  // Subregister 2 of Multireg challenge
  // R[challenge_2]: V(False)
  logic challenge_2_qe;
  logic [0:0] challenge_2_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_challenge2_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&challenge_2_flds_we),
    .q_o(challenge_2_qe)
  );
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_challenge_2 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (challenge_2_we),
    .wd     (challenge_2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (challenge_2_flds_we[0]),
    .q      (reg2hw.challenge[2].q),
    .ds     (),

    // to register interface (read)
    .qs     (challenge_2_qs)
  );
  assign reg2hw.challenge[2].qe = challenge_2_qe;


  // Subregister 3 of Multireg challenge
  // R[challenge_3]: V(False)
  logic challenge_3_qe;
  logic [0:0] challenge_3_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_challenge3_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&challenge_3_flds_we),
    .q_o(challenge_3_qe)
  );
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_challenge_3 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (challenge_3_we),
    .wd     (challenge_3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (challenge_3_flds_we[0]),
    .q      (reg2hw.challenge[3].q),
    .ds     (),

    // to register interface (read)
    .qs     (challenge_3_qs)
  );
  assign reg2hw.challenge[3].qe = challenge_3_qe;


  // Subregister 0 of Multireg response
  // R[response_0]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRO),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_response_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (1'b0),
    .wd     ('0),

    // from internal hardware
    .de     (hw2reg.response[0].de),
    .d      (hw2reg.response[0].d),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.response[0].q),
    .ds     (),

    // to register interface (read)
    .qs     (response_0_qs)
  );


  // Subregister 1 of Multireg response
  // R[response_1]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRO),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_response_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (1'b0),
    .wd     ('0),

    // from internal hardware
    .de     (hw2reg.response[1].de),
    .d      (hw2reg.response[1].d),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.response[1].q),
    .ds     (),

    // to register interface (read)
    .qs     (response_1_qs)
  );


  // Subregister 2 of Multireg response
  // R[response_2]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRO),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_response_2 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (1'b0),
    .wd     ('0),

    // from internal hardware
    .de     (hw2reg.response[2].de),
    .d      (hw2reg.response[2].d),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.response[2].q),
    .ds     (),

    // to register interface (read)
    .qs     (response_2_qs)
  );


  // Subregister 3 of Multireg response
  // R[response_3]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRO),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_response_3 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (1'b0),
    .wd     ('0),

    // from internal hardware
    .de     (hw2reg.response[3].de),
    .d      (hw2reg.response[3].d),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.response[3].q),
    .ds     (),

    // to register interface (read)
    .qs     (response_3_qs)
  );


  // Subregister 4 of Multireg response
  // R[response_4]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRO),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_response_4 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (1'b0),
    .wd     ('0),

    // from internal hardware
    .de     (hw2reg.response[4].de),
    .d      (hw2reg.response[4].d),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.response[4].q),
    .ds     (),

    // to register interface (read)
    .qs     (response_4_qs)
  );


  // Subregister 5 of Multireg response
  // R[response_5]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRO),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_response_5 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (1'b0),
    .wd     ('0),

    // from internal hardware
    .de     (hw2reg.response[5].de),
    .d      (hw2reg.response[5].d),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.response[5].q),
    .ds     (),

    // to register interface (read)
    .qs     (response_5_qs)
  );


  // Subregister 6 of Multireg response
  // R[response_6]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRO),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_response_6 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (1'b0),
    .wd     ('0),

    // from internal hardware
    .de     (hw2reg.response[6].de),
    .d      (hw2reg.response[6].d),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.response[6].q),
    .ds     (),

    // to register interface (read)
    .qs     (response_6_qs)
  );


  // Subregister 7 of Multireg response
  // R[response_7]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRO),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_response_7 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (1'b0),
    .wd     ('0),

    // from internal hardware
    .de     (hw2reg.response[7].de),
    .d      (hw2reg.response[7].d),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.response[7].q),
    .ds     (),

    // to register interface (read)
    .qs     (response_7_qs)
  );



  logic [13:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[ 0] = (reg_addr == PUF_CTRL_SIGNALS_OFFSET);
    addr_hit[ 1] = (reg_addr == PUF_STATE_SIGNALS_OFFSET);
    addr_hit[ 2] = (reg_addr == PUF_CHALLENGE_0_OFFSET);
    addr_hit[ 3] = (reg_addr == PUF_CHALLENGE_1_OFFSET);
    addr_hit[ 4] = (reg_addr == PUF_CHALLENGE_2_OFFSET);
    addr_hit[ 5] = (reg_addr == PUF_CHALLENGE_3_OFFSET);
    addr_hit[ 6] = (reg_addr == PUF_RESPONSE_0_OFFSET);
    addr_hit[ 7] = (reg_addr == PUF_RESPONSE_1_OFFSET);
    addr_hit[ 8] = (reg_addr == PUF_RESPONSE_2_OFFSET);
    addr_hit[ 9] = (reg_addr == PUF_RESPONSE_3_OFFSET);
    addr_hit[10] = (reg_addr == PUF_RESPONSE_4_OFFSET);
    addr_hit[11] = (reg_addr == PUF_RESPONSE_5_OFFSET);
    addr_hit[12] = (reg_addr == PUF_RESPONSE_6_OFFSET);
    addr_hit[13] = (reg_addr == PUF_RESPONSE_7_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[ 0] & (|(PUF_PERMIT[ 0] & ~reg_be))) |
               (addr_hit[ 1] & (|(PUF_PERMIT[ 1] & ~reg_be))) |
               (addr_hit[ 2] & (|(PUF_PERMIT[ 2] & ~reg_be))) |
               (addr_hit[ 3] & (|(PUF_PERMIT[ 3] & ~reg_be))) |
               (addr_hit[ 4] & (|(PUF_PERMIT[ 4] & ~reg_be))) |
               (addr_hit[ 5] & (|(PUF_PERMIT[ 5] & ~reg_be))) |
               (addr_hit[ 6] & (|(PUF_PERMIT[ 6] & ~reg_be))) |
               (addr_hit[ 7] & (|(PUF_PERMIT[ 7] & ~reg_be))) |
               (addr_hit[ 8] & (|(PUF_PERMIT[ 8] & ~reg_be))) |
               (addr_hit[ 9] & (|(PUF_PERMIT[ 9] & ~reg_be))) |
               (addr_hit[10] & (|(PUF_PERMIT[10] & ~reg_be))) |
               (addr_hit[11] & (|(PUF_PERMIT[11] & ~reg_be))) |
               (addr_hit[12] & (|(PUF_PERMIT[12] & ~reg_be))) |
               (addr_hit[13] & (|(PUF_PERMIT[13] & ~reg_be)))));
  end

  // Generate write-enables
  assign ctrl_signals_we = addr_hit[0] & reg_we & !reg_error;

  assign ctrl_signals_enable_puf_wd = reg_wdata[0];

  assign ctrl_signals_mode_puf_wd = reg_wdata[1];

  assign ctrl_signals_ready_cha_wd = reg_wdata[2];
  assign challenge_0_we = addr_hit[2] & reg_we & !reg_error;

  assign challenge_0_wd = reg_wdata[31:0];
  assign challenge_1_we = addr_hit[3] & reg_we & !reg_error;

  assign challenge_1_wd = reg_wdata[31:0];
  assign challenge_2_we = addr_hit[4] & reg_we & !reg_error;

  assign challenge_2_wd = reg_wdata[31:0];
  assign challenge_3_we = addr_hit[5] & reg_we & !reg_error;

  assign challenge_3_wd = reg_wdata[31:0];

  // Assign write-enables to checker logic vector.
  always_comb begin
    reg_we_check = '0;
    reg_we_check[0] = ctrl_signals_we;
    reg_we_check[1] = 1'b0;
    reg_we_check[2] = challenge_0_we;
    reg_we_check[3] = challenge_1_we;
    reg_we_check[4] = challenge_2_we;
    reg_we_check[5] = challenge_3_we;
    reg_we_check[6] = 1'b0;
    reg_we_check[7] = 1'b0;
    reg_we_check[8] = 1'b0;
    reg_we_check[9] = 1'b0;
    reg_we_check[10] = 1'b0;
    reg_we_check[11] = 1'b0;
    reg_we_check[12] = 1'b0;
    reg_we_check[13] = 1'b0;
  end

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = ctrl_signals_enable_puf_qs;
        reg_rdata_next[1] = ctrl_signals_mode_puf_qs;
        reg_rdata_next[2] = ctrl_signals_ready_cha_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[0] = state_signals_response_valid_bit_qs;
        reg_rdata_next[1] = state_signals_response_done_2bit_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = challenge_0_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = challenge_1_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[31:0] = challenge_2_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[31:0] = challenge_3_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[31:0] = response_0_qs;
      end

      addr_hit[7]: begin
        reg_rdata_next[31:0] = response_1_qs;
      end

      addr_hit[8]: begin
        reg_rdata_next[31:0] = response_2_qs;
      end

      addr_hit[9]: begin
        reg_rdata_next[31:0] = response_3_qs;
      end

      addr_hit[10]: begin
        reg_rdata_next[31:0] = response_4_qs;
      end

      addr_hit[11]: begin
        reg_rdata_next[31:0] = response_5_qs;
      end

      addr_hit[12]: begin
        reg_rdata_next[31:0] = response_6_qs;
      end

      addr_hit[13]: begin
        reg_rdata_next[31:0] = response_7_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // shadow busy
  logic shadow_busy;
  assign shadow_busy = 1'b0;

  // register busy
  assign reg_busy = shadow_busy;

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT_PULSE(wePulse, reg_we, clk_i, !rst_ni)
  `ASSERT_PULSE(rePulse, reg_re, clk_i, !rst_ni)

  `ASSERT(reAfterRv, $rose(reg_re || reg_we) |=> tl_o_pre.d_valid, clk_i, !rst_ni)

  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit), clk_i, !rst_ni)

  // this is formulated as an assumption such that the FPV testbenches do disprove this
  // property by mistake
  //`ASSUME(reqParity, tl_reg_h2d.a_valid |-> tl_reg_h2d.a_user.chk_en == tlul_pkg::CheckDis)

endmodule
